### ISSUE TITLE
Not able to run application on Windows 2003 and glassfish 2

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#590]
After deploying application on glassfish 2 over windows 2003, homepage was always reloading itself, not allowing any operation on the page neither selecting any other option.
This has not happened on glassfish 3 over linux.

On the log, there is the following error:
 org.cerberus.servlet.guipages.Homepage
java.lang.ClassNotFoundException: org.cerberus.servlet.guipages.Homepage
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1578)
	at org.apache.catalina.core.StandardWrapper.loadServletClass(StandardWrapper.java:1273)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1049)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:848)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invokeInternal(StandardContextValve.java:287)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:218)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:648)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:593)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:94)
	at com.sun.enterprise.web.PESessionLockingStandardPipeline.invoke(PESessionLockingStandardPipeline.java:98)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:222)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:648)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:593)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:587)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:1093)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:166)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:648)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:593)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:587)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:1093)
	at org.apache.coyote.tomcat5.CoyoteAdapter.service(CoyoteAdapter.java:291)
	at com.sun.enterprise.web.connector.grizzly.DefaultProcessorTask.invokeAdapter(DefaultProcessorTask.java:666)
	at com.sun.enterprise.web.connector.grizzly.DefaultProcessorTask.doProcess(DefaultProcessorTask.java:597)
	at com.sun.enterprise.web.connector.grizzly.DefaultProcessorTask.process(DefaultProcessorTask.java:872)
	at com.sun.enterprise.web.connector.grizzly.DefaultReadTask.executeProcessorTask(DefaultReadTask.java:341)
	at com.sun.enterprise.web.connector.grizzly.DefaultReadTask.doTask(DefaultReadTask.java:263)
	at com.sun.enterprise.web.connector.grizzly.DefaultReadTask.doTask(DefaultReadTask.java:214)
	at com.sun.enterprise.web.portunif.PortUnificationPipeline$PUTask.doTask(PortUnificationPipeline.java:382)
	at com.sun.enterprise.web.connector.grizzly.TaskBase.run(TaskBase.java:264)
	at com.sun.enterprise.web.connector.grizzly.ssl.SSLWorkerThread.run(SSLWorkerThread.java:106)
|#]

Had to rollback the installation, although keeping the database version.

**Comment by cjmachado** [comment]
Please correct me if I'm wrong but I took a look at HomePage source code and it's using this annotation: javax.servlet.annotation.WebServlet. Isn't this annotation only supported in JavaEE 6? Glassfish 2 only supports JavaEE 5, so this could be the cause of the issue.

**Comment by cjmachado** [comment]
Maybe I'm wrong. This annotation is used at deployment time only.

**Comment by bcivel** [comment]
You may have java6 installed on your server because this annotation is used in many servlet, since a couple a months.

Error raised on the log seems to be not related to the glassfish version. Some package renaming have been done and it look like the cleaning process didn't work well, or something like that.

To be honnest, information are not enough consistent for me to dig. I'm waiting for an access to a glassfish 2.1.1 environment to try to reproduce it and understand where does it come from.

**Comment by gmoita** [comment]
Any update?
I'm not able to have give any more information without impacting the application usage, this is, deploying again and breaking a cluster.

**Comment by bcivel** [comment]
Updating issue for everyone being aware on next steps.
Error seems not related to Glassfish2 as it work on other Glassfish2 configuration.
Seems to be more related to something like a caching issue following the renaming of one package into the same name in lowercase (org.cerberus.servlet.guipages).
Next step would be to undeploy, clean and deploy again manually. In case of failure, let's create a new cluster and deploy it on this new cluster. 
Anyway, @corentindms pushed a correction to avoid  the page to reload automatically on error, which will allow to use the application without having the browser reloading everytime.

**Comment by bcivel** [comment]
Solved
