### ISSUE TITLE
Deploy links not available

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#773]
Hi.
We've tested the deploy from the Environment.jsp page and deploy links are not shown.
We tried to do a deploy on system VCCRM, country BE, environment UAT and tried to deploy revision R07700.
We see the revision content, but no deploy links.
We went to the QA server logs and we see exception on the logs.
The exception is:
[#|2016-05-20T12:30:09.154+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=118;_ThreadName=Thread-2;|2016-05-20 12:30:09 ERROR CountryEnvDeployTypeDAO:176 - Unable to execute query : java.sql.SQLException: No value specified for parameter 4
|#]

[#|2016-05-20T12:30:09.154+0200|SEVERE|glassfish3.1.2|org.cerberus.servlet.crud.buildrevisionchange.ReadBuildRevisionParameters|_ThreadID=118;_ThreadName=Thread-2;|org.cerberus.exception.CerberusException
        at org.cerberus.crud.service.impl.CountryEnvDeployTypeService.convert(CountryEnvDeployTypeService.java:168)
        at org.cerberus.servlet.crud.buildrevisionchange.ReadBuildRevisionParameters.findSVNBuildRevisionParametersBySystem(ReadBuildRevisionParameters.java:314)
        at org.cerberus.servlet.crud.buildrevisionchange.ReadBuildRevisionParameters.processRequest(ReadBuildRevisionParameters.java:131)
        at org.cerberus.servlet.crud.buildrevisionchange.ReadBuildRevisionParameters.doGet(ReadBuildRevisionParameters.java:173)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:281)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
        at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
        at com.sun.grizzly.http.ajp.AjpProcessorTask.invokeAdapter(AjpProcessorTask.java:135)
        at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
        at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
        at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
        at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
        at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
        at java.lang.Thread.run(Thread.java:722)

This is critical.

**Comment by vertigo17** [comment]
Fix has been done based on the log but I was not available to reproduce it so I don't close the issue and let you close it once you tested it.

**Comment by gmoita** [comment]
Working ok.
I was able to submit the deploy execution and it started.
