### ISSUE TITLE
NPE is thrown when a test case has only Target Rev field filled

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#940]
Tests that are marked with a Target Rev only are throwing a NPE with the following stack trace:

[#|2016-09-23T11:54:38.226+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=154;_ThreadName=Thread-2;|2016-09-23 11:54:38 ERROR RunTestCase:349 - Error while executing RunTestCase 
java.lang.NullPointerException
	at org.cerberus.engine.execution.impl.ExecutionCheckService.compareBuild(ExecutionCheckService.java:322)
	at org.cerberus.engine.execution.impl.ExecutionCheckService.checkTargetBuildRevision(ExecutionCheckService.java:237)
	at org.cerberus.engine.execution.impl.ExecutionCheckService.checkTestCaseExecution(ExecutionCheckService.java:87)
	at org.cerberus.engine.execution.impl.ExecutionStartService.startExecution(ExecutionStartService.java:330)
	at org.cerberus.engine.execution.impl.RunTestCaseService.runTestCase(RunTestCaseService.java:56)
	at org.cerberus.servlet.zzpublic.RunTestCase.doGet(RunTestCase.java:346)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
(...)
|#]

Test case results in a PE and is not included in the ExecutionReportByTag page. Example TC where this error occurs: [PAGE VCCRM Customer|0011P|IT|QA]

**Comment by bcivel** [comment]
Hello @cjmachado 
it was not that easy to reproduce as the example you provided finally works :-)
In fact, I think it was probably due to environment Build/Rev that was inserted without being present in buildrevision definition page, or that was not defined. 
This is not possible anymore since the refactoring of the interface. 
Nevertheless, I protected the code to deliver a clear error message if it happen again.

Thanks for your contribution
Benoit
